raw_data_1: '../01_data/PDB_31-07-2011.csv'
raw_data_2: '../01_data/PDB_31-12-2012.csv'
data: '../01_data/data.csv'
new_data: '../01_data/new_data.csv'
xy: '../01_data/xy.csv'
xy_06: '../01_data/xy_06.csv'

x_sum_np: '../01_data/x_sum_np.csv'